sudo: false
language: generic

os:
- linux
- osx

python:
- "3.5"

cache:
  # For faster build times.
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

addons:
  apt:
    packages:
    - cmake
    - libgmp-dev       # for cabal
    - libblas-dev      # for hmatrix
    - liblapack-dev
    - python3          # for paganini
    - python3-pip
    - python3-setuptools

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH

- echo $TRAVIS_OS_NAME

# Install stack.
- |
  if [ $TRAVIS_OS_NAME = linux ]
    then
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    else
      travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  fi

# Install python on OSX.
- |
  if [ $TRAVIS_OS_NAME = osx ]
    then
      brew update
      brew upgrade python
      brew postinstall python -dv

      # Travis does not officialy support python on macos
      # see https://docs.travis-ci.com/user/languages/python/
      # We need a build for both linux and macos, so I put an alias
      alias python3='python'
      alias pip3='pip'
  fi

# Console output corrent python version
- python3 --version

# Install paganini dependencies.
- pip3 install --user --upgrade pip
- pip3 install --user numpy scipy
- pip3 install --user cvxpy six
- pip3 install --user paganini

install:
# Install medulla/paganini.
- cd $TRAVIS_BUILD_DIR/medulla
- python3 setup.py install --user --prefix=
- cd $TRAVIS_BUILD_DIR

# Compile boltzmann-brain and its dependencies.
- stack install happy
- stack --no-terminal --install-ghc test --only-dependencies --ghc-options=-Werror
- stack install --ghc-options=-Werror

script:
# Compile haddock etc.
- stack --no-terminal test --haddock --no-haddock-deps

before_deploy:
# Rename boltzmann-brain binaries according to the OS.
- |
  if [ $TRAVIS_OS_NAME = linux ]
    then
      mv $HOME/.local/bin/bb $HOME/.local/bin/bb-x86_64-linux
    else
      mv $HOME/.local/bin/bb $HOME/.local/bin/bb-x86_64-osx
  fi

# Deploy boltzmann-brain to github releases.
deploy:
  - provider: releases
    api_key:
      secure: jw3HDOEci9NLYT4gdzyRWHMPuAOAhLO6i5UmOpP0UyCVW6TKaIJvscXmavw/bSV30HjWLi/NWeKAl/f0bGgMLY/8t+s4VfhJ0Z6dgdXzOmuHRIwej6HOiPTSWvrZZ1my7bRfFaVTXkEiSGGeSjS/iiSON4hTIPyjfL3xKFViBKnBsItpHwxu3ppIbsHsebgu+1l5nV62UbmQ+qtUyfk8yIUrGu3YM+qVHgxz1p4idLBNzSxpvh8nWq+oX3aOTj7eAD2iXMdR+lqOQTC45Le8D12q50v3rDDdTh4JHPRKbJo0GDn0lPDfO+XCzJeqiktFQ27C5BftR5to9PxkE7OYvcdtZBM8hwp4aCAAWRRwa/t8wsXIsXjmRRHa5qkgmxIwmzcdFNy8z8qxJ6etQIluQBLi9vPWIICf2ZQUzgCnAHYu2NiyewJJvTcB00tdsTGYESa1wYq5ZCgaVbyyI+TprjOS54WeuWXBgBMR4Bd/Y9MSZeOl7c60qtLC7bcWk1gchcoGgjTvyzshN4oyfozUULE75DI3q+HXp7uM9m1YIUAmEQ6Ye+jaSCD2qgjMsYqYS1ww9y0fdc2W8S26nHIjXKYWFFysh2PaetbHZ9a3Qv0+FA+z0KYR5Jp4kf/MjJcZKY86sMqq3cWDjlxjrgbpXgZsvaV4HfKjJdTJpqr/DiI=
    file_glob: true
    file:
      - "$HOME/.local/bin/bb-x86_64-linux"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: jw3HDOEci9NLYT4gdzyRWHMPuAOAhLO6i5UmOpP0UyCVW6TKaIJvscXmavw/bSV30HjWLi/NWeKAl/f0bGgMLY/8t+s4VfhJ0Z6dgdXzOmuHRIwej6HOiPTSWvrZZ1my7bRfFaVTXkEiSGGeSjS/iiSON4hTIPyjfL3xKFViBKnBsItpHwxu3ppIbsHsebgu+1l5nV62UbmQ+qtUyfk8yIUrGu3YM+qVHgxz1p4idLBNzSxpvh8nWq+oX3aOTj7eAD2iXMdR+lqOQTC45Le8D12q50v3rDDdTh4JHPRKbJo0GDn0lPDfO+XCzJeqiktFQ27C5BftR5to9PxkE7OYvcdtZBM8hwp4aCAAWRRwa/t8wsXIsXjmRRHa5qkgmxIwmzcdFNy8z8qxJ6etQIluQBLi9vPWIICf2ZQUzgCnAHYu2NiyewJJvTcB00tdsTGYESa1wYq5ZCgaVbyyI+TprjOS54WeuWXBgBMR4Bd/Y9MSZeOl7c60qtLC7bcWk1gchcoGgjTvyzshN4oyfozUULE75DI3q+HXp7uM9m1YIUAmEQ6Ye+jaSCD2qgjMsYqYS1ww9y0fdc2W8S26nHIjXKYWFFysh2PaetbHZ9a3Qv0+FA+z0KYR5Jp4kf/MjJcZKY86sMqq3cWDjlxjrgbpXgZsvaV4HfKjJdTJpqr/DiI=
    file_glob: true
    file:
      - "$HOME/.local/bin/bb-x86_64-osx"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx
